# This message is sent when the isis neighbor is up
#Jul 27 18:35:13 HOSTNAME Isis: Instance 0: %ISIS-4-ISIS_ADJCHG: L2 Neighbor State Change for SystemID 2080.6521.2080 on et5 to UP
messages:
  - error: ISIS_NEIGHBOR_UP
    tag: ISIS-4-ISIS_ADJCHG
    values:
      neighbor: (\S+)
      interface: (\S+)
      level: (L\d)
    line: '{level} Neighbor State Change for SystemID {neighbor} on {interface} to UP'
    model: openconfig-isis
    mapping:
      static:
        network-instances//network-instance//global//protocols//protocol//isis//interfaces//interface//{interface}//levels//level//{level}//adjacencies//adjacency//{neighbor}//state//adjacency-state: UP
      variables: {}
