language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
install:
  - pip install tox-travis
  - pip install coveralls
deploy:
  - provider: pypi
    user: mirucha
    password:
      secure: "p971DB8HxHvIEfSg5l3UjicCxAmBqFV0tnj8Em8FRIGvOZEHgbCuLpSNSWdr5X8KFpLq+5W0uUJhzLj6lTQFXZXfqclDq8SLT7CdJCT62xjM5NvIWV0znS3A6TBBJsY/rTpEnxK3PuFbyn4WLRE624IG8xe8J2M8AYMlRrs4RFRh3DNA/mbgd6pi7uV/cYFu6OLp0Asu0bSV1BqU3aJFX//FJ3RYjknwCyV8JAly1eiDTgYprNP13oCDsNFkBa6Dn0BaPn /vYZei7D/ismooLxdlLY0NUAjbpqppj6Fuyb+/aBa2Dp7udxReS4/9rX0fIXl7q+qqMdkp5N6+W9jILa4Ykr0a37348IDx2GpD1+PdYzZTdC1m7JqKfAZ/YV+f7RNuZoUQz1fumx7993QYk2n4ONUkTIFbjakzZf9Ylh0ISo7ym461RHl/mIJh94DvFifkqkNVgWeBX1wyS1UCa+wqTnYEg50Mdgvhj0ZcQxKv5ZMUh6fiK3bS/fBO084Lkyd0dggEdjB42tqCd4s0sL2SI 5/2M5D+yYqq6NZX15i/GjpQmeee/Gwv5YWHB/GOA8+jFEpGa8Em630b8jpoxN/o5GYJTAoVcqe3mvEjXeb0Ga7Oeo1TNlrcBYsZHrN/mL4aS+c3XSm4HATKdY1vsntP5R9hevtHObXRjTjcXik="
    on:
      tags: true
      branch: master
script:
- tox
after_success:
- coveralls
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/napalm-logs; fi
