# This error tag corresponds to syslog messages notifying that the configured
# bgp neighbor has changed state
messages:
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: BGP
    values:
      instance: (\S*)
      peer: ([\w\d:\.]+)
#      reason: (.*)
    line: 'neighbor {peer} vpn vrf {instance} Up'
    model: openconfig-bgp
    mapping:
#      variables:
#        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: ESTABLISHED
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: BGP
    values:
      instance: (\S*)
      peer: ([\w\d:\.]+)
      reason: (.*)
    line: 'neighbor {peer} vpn vrf {instance} Down {reason}'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: BGP
    values:
      peer: ([\w\d:\.]+)
#      reason: (.*)
    line: 'neighbor {peer} Up'
    model: openconfig-bgp
    mapping:
 #     variables:
 #       bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: ESTABLISHED
  - error: BGP_NEIGHBOR_STATE_CHANGED
    tag: BGP
    values:
      peer: ([\w\d:\.]+)
      reason: (.*)
    line: 'neighbor {peer} Down {reason}'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: IDLE
