messages:
  - error: BGP_NEIGHBOR_UP_DEFAULT_VRF
    tag: BGP
    values:
      peer: ([\w\d:\.]+)
      reason: ([^\(\)]+)
    line: 'Peer (VRF: default-vrf) {peer} UP ({reason})'
    model: openconfig-bgp
    mapping:
      variables:
        bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        bgp//neighbors//neighbor//{peer}//state//session-state: ESTABLISHED
        bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_CONFIRM
  - error: BGP_NEIGHBOR_UP_WITHIN_VRF
    tag: BGP
    values:
      instance: (\w+)
      peer: ([\w\d:\.]+)
      reason: ([^\(\)]+)
    line: 'Peer (VRF: {instance}) {peer} UP ({reason})'
    model: openconfig-network-instance
    mapping:
      variables:
        network-instances//network-instance//{instance}//protocols//bgp//bgp//neighbors//neighbor//{peer}//state//session-state-change-event: reason
      static:
        network-instances//network-instance//{instance}//protocols//bgp//bgp//neighbors//neighbor//{peer}//state//session-state: ESTABLISHED
        network-instances//network-instance//{instance}//protocols//bgp//bgp//neighbors//neighbor//{peer}//state//session-state-old: OPEN_CONFIRM
