# This message is sent when the isis neighbor is down
#Mar  4 09:15:48 HOSTNAME ISIS: L2 Neighbor 2080.6521.2083 Down on ve 172 due to BFD Trigger
messages:
  - error: ISIS_NEIGHBOR_DOWN
    tag: ISIS-4-ISIS_ADJCHG
    values:
      neighbor: (\S+)
      interface: (\S+)
      instance: (\S+)
      level: (L\d)
      downReason: (.*)
    line: '{level} Neighbor {neighbor} Down on {interface} {instance} due to {downReason}'
    model: openconfig-isis
    mapping:
      variables:
        network-instances//network-instance//global//protocols//protocol//isis//interfaces//interface//{interface}_{instance}//levels//level//{level}//adjacencies//adjacency//{neighbor}//state//adjacency-state-change-reason-message: downReason
      static:
        network-instances//network-instance//global//protocols//protocol//isis//interfaces//interface//{interface}_{instance}//levels//level//{level}//adjacencies//adjacency//{neighbor}//state//adjacency-state: DOWN
